### ISSUE TITLE
PHP options are not picked up by PHP

### ISSUE THREAD

**Issue by webdevian** [oscarotero/php-server-manager#1]
Because the script is being declared before the options, it should be the other way around https://secure.php.net/manual/en/features.commandline.options.php

**Comment by webdevian** [comment]
@oscarotero The version 1.2.0 you've pushed to NPM doesn't seem to have my PRs in

https://registry.npmjs.org/php-server-manager/-/php-server-manager-1.2.0.tgz

**Comment by oscarotero** [comment]
I see your PRs in the package (the promise and the stdio option). The only thing is the reorder of the script. The initial change was reverted here: https://github.com/oscarotero/php-server-manager/commit/4ad0b02e3a8e16de45d0bdb8b3fc7dc120e2fd14

**Comment by webdevian** [comment]
Ah right, I reverted the change in one of the other pull requests. I forgot that if they were all merged this would take precedence and reintroduce #1, my mistake :(

4ad0b02 now needs to be reverted to fix #1

**Comment by oscarotero** [comment]
Released 1.2.1 including this change.
Thanks for your contributions!
