### ISSUE TITLE
Hide PHP console window

### ISSUE THREAD

**Issue by mikemania** [oscarotero/php-server-manager#11]
When I build my electron application and then run it, a PHP server console window opens in addition to the application window. Closing this console window stops the PHP server. Is there any way to hide this window?

**Comment by oscarotero** [comment]
No idea. This library uses [child process API](https://nodejs.org/api/child_process.html) to run the command. Maybe there's an option for that.

[Looking at the documentation](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback), there's a `windowsHide` option, not sure if it can fix the issue.

**Comment by mikemania** [comment]
Thank you. Setting that option does fix the problem.
