### ISSUE TITLE
PHP server not started. Retrying Electron

### ISSUE THREAD

**Issue by ziobru** [oscarotero/php-server-manager#8]
I was using this module to start a php webserver inside my electron app. All works fine, the server will start correctly, but in the console it will be logged until I exit from the app this message: `PHP server not started. Retrying...` 
I read the other issue about the child process, but I don't think this is related to my issue. Any solution to solve this?

**Comment by oscarotero** [comment]
Are you sure the server is already started, and is the same than the one used?
If so, can you create a simple github repo replicating this error to try to fix it?

**Comment by ziobru** [comment]
Yes, the server is running, the console will log this output that is supposed to displayed if the built-in server is running.
`PHP 7.1.16 Development Server started at Wed Oct 31 12:10:44 2018
Listening on http://localhost:8000
Document root is /Applications/MAMP/htdocs/electrontut/res
Press Ctrl-C to quit.` 

I've disabled the output `console.error()` inside the index.js file of the php-server-manager plugin.
I think the problem is with the cb function? I have no callback but only the config of the server I want to start that I run using this code. 

`const { app, BrowserWindow } = require('electron');
const electron = require('electron');
const Menu = electron.Menu
const path = require('path');
const url = require('url');
// PHP SERVER CREATION /////
const PHPServer = require('php-server-manager');

const server = new PHPServer({
  host: 'localhost',
  port: 8000,
  directory: path.resolve(__dirname)+'/res/',
  stdio: 'inherit',
  directives: {
      display_errors: 1,
      expose_php: 0
  }
});

app.on('ready', () => {

  createWindow();
  server.run(); 
});`

**Comment by oscarotero** [comment]
This error can happen for two reasons:
- The `localhost` host is not correctly configured. In that case, leave the default value (127.0.0.1)
- The directory does not exist.

Try with this config:

```js
const server = new PHPServer({
  directory: path.resolve(__dirname)+'/res/',
  directives: {
      display_errors: 1,
      expose_php: 0
  }
});
```

**Comment by oscarotero** [comment]
localhost is just a hostname that normally resolves to 127.0.0.1 (the ip for the local server). These hostnames are mapped to ips in the host file in the operating system. This may be configured incorrectly (or not configured at all), so it's safer to use the ip instead the hostname.

You can see more info here: https://en.wikipedia.org/wiki/Localhost

**Comment by ziobru** [comment]
> localhost is just a hostname that normally resolves to 127.0.0.1 (the ip for the local server). These hostnames are mapped to ips in the host file in the operating system. This may be configured incorrectly (or not configured at all), so it's safer to use the ip instead the hostname.
> 
> You can see more info here: https://en.wikipedia.org/wiki/Localhost

Ok, perfect. Thanks for the clarification.

**Comment by ashu-ch** [comment]
@ghost
can share your main.js code

**Comment by ashu-ch** [comment]
this is my main.js file
if I install php in my system it's working and if I uninstall it's not working
it should run the php from php directory of the app but it's throwing error server is not started

const electron = require('electron')
const path = require('path')

const BrowserWindow = electron.BrowserWindow
const app = electron.app

app.on('ready', () => {
    createWindow()
})

var phpServer = require('php-server-manager');
const PHPServer = require('php-server-manager');
const port = 8001, host = '127.0.0.1';
const serverUrl = `http://${host}:${port}`;


const server = new PHPServer({
    php: `${__dirname}/php`,
    stdio: 'inherit',
    port: 8001,
    directory: `${__dirname}/www/public`,
    directives: {
        display_errors: 1,
        expose_php: 1
    },
    config: `${__dirname}/php/php.ini`,
    script: `${__dirname}/www/server.php`,
});

let mainWindow

function createWindow() {
    // Create a PHP Server

    server.run();

    // phpServer.createServer({
    //   port: port,
    //   hostname: host,
    //   base: `${__dirname}/www/public`,
    //   keepalive: false,
    //   open: false,
    //   bin: `${__dirname}/php/php.exe`,
    //   router: __dirname + '/www/server.php'
    // });

    // Create the browser window.
    const {
        width,
        height
    } = electron.screen.getPrimaryDisplay().workAreaSize
    mainWindow = new BrowserWindow({
        width: width,
        height: height,
        show: false,
        autoHideMenuBar: true
    })

    mainWindow.loadURL(serverUrl)

    mainWindow.webContents.once('dom-ready', function () {
        mainWindow.show()
        mainWindow.maximize();
        // mainWindow.webContents.openDevTools()
    });



    // Emitted when the window is closed.
    mainWindow.on('closed', function () {
        server.close();
        mainWindow = null;
    })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
//app.on('ready', createWindow) // <== this is extra so commented, enabling this can show 2 windows..

// Quit when all windows are closed.
app.on('window-all-closed', function () {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
        // PHP SERVER QUIT
        server.close();
        app.quit();
    }
})

app.on('activate', function () {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (mainWindow === null) {
        createWindow()
    }
})
